### ISSUE TITLE
Reported missing files

### ISSUE THREAD

**Issue by Ava7** [datacharmer/mysql-sandbox#1]
I know nothing about perl, but was asked to inform the author about these so here they are.

    # perl Makefile.PL 
    Checking if your kit is complete...
    Warning: the following files are missing in your kit:
        MYMETA.json
        MYMETA.yml
    Please inform the author.
    Writing Makefile for MySQL::Sandbox

No installation issues though, the program works like a charm.
Thanks :heart:!

**Comment by datacharmer** [comment]
Hi!
Thanks for your report!
These two files are created when we execute Makefile.PL. 
I have removed them from the MANIFEST
