### ISSUE TITLE
start script reports failure because of timeout even though server starts

### ISSUE THREAD

**Issue by msestak** [datacharmer/mysql-sandbox#11]
Start script (bash script that starts server) can sometimes report failure "sandbox server not started yet" because some (re)starts require more than hard coded  TIMEOUT=60 (line 1098 MySQL/Sandbox/Scripts.pm). 
One example is recreating large InnoDB logs on slow disks. Script reports failure, however, MySQL server starts but not in 60 seconds.
One solution would be to increase this timeout value but then user would wait longer for real failure.
So this is mostly for info.

**Comment by datacharmer** [comment]
Thanks for the report. 
There should not be any problem if we increase the timeout. The start script works by checking continuously for a PID file being generated. When it is found, the script exits successfully, which could happen after 1 second or 59 seconds. I thought 60 was a good timeout for a failure, but I will increase it.  I will first run a few tests and see if increasing the timeout produces any side effects.

**Comment by datacharmer** [comment]
This issue is fixed in MySQL-Sandbox 3.1.03
