### ISSUE TITLE
how to set 'SANDBOX_AS_ROOT'

### ISSUE THREAD

**Issue by zhangshengdong** [datacharmer/mysql-sandbox#15]
[root@localhost arp]# make_replication_sandbox --how_many_slaves=3 --sandbox_base_port=21288 --upper_directory=/arp/Zmysql /arp/mysql-5.6.29.tar.gz
MySQL Sandbox should not run as root

If you know what you are doing and want to
 run as root nonetheless, please set the environment
variable 'SANDBOX_AS_ROOT' to a nonzero value

**Comment by datacharmer** [comment]
If you are asking this question, you seem to contradict the warning message. So I urge you to run MySQL Sandbox as a regular user, NOT as root.

If you still want to go ahead, the command is
export SANDBOX_AS_ROOT=1

**Comment by zhangshengdong** [comment]
thanks for your reply
