### ISSUE TITLE
mysql 5.7 replication sandbox can't install

### ISSUE THREAD

**Issue by clarkk** [datacharmer/mysql-sandbox#16]
```
mysql_test@dyntest-athlon-3700-2gb:/var/bin$ make_replication_sandbox mysql-server_5.7.11-1debian8_amd64.deb-bundle.tar
installing and starting master
error installing the master

(256 )
```

**Comment by datacharmer** [comment]
You are using the wrong tarball. THe one you mention contains .deb packages instead of executables.

The tarball you should use is the one containing the MySQL binaries, such as, for example:
https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.11-linux-glibc2.5-i686.tar.gz

**Comment by clarkk** [comment]
I can only find two tarball files..

The first one and this
https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-server_5.7.11-1debian7_amd64.deb-bundle.tar

None of the two works..

I'm running Debian 64 bit

Is the one you posted for Debian 64 bit?

**Comment by datacharmer** [comment]
The one that I posted is generic Linux. It works on any flavor of Linux (except Alpine, which does not have glibc).

**Comment by clarkk** [comment]
Ok, I'll try it out later today.. :)

But where did you find it? So I can find new releases later

**Comment by clarkk** [comment]
I still get an error

```
$ make_replication_sandbox mysql-5.7.11-linux-glibc2.5-i686.tar.gz
installing and starting master
error while creating grant tables

error installing the master

(512 )
```

**Comment by datacharmer** [comment]
I have no idea of what you are trying to do with the above commands. MySQL Sandbox is used as a regular user (not root) and you don't need to create directories or users.

Anyway, to understand what is failing, please do the following:
1) remove ~/sandboxes/rsandbox*
2) run 
     SBDEBUG=2 make_sandbox mysql-5.7.11-linux-glibc2.5-i686.tar.gz

This will create a single sandbox, and report the errors with more detail
