### ISSUE TITLE
Add mysqlsh script to sandbox

### ISSUE THREAD

**Issue by datacharmer** [datacharmer/mysql-sandbox#17]
MySQL 5.7.12 adds a new protocol and the ability of running queries in a [new shell](http://mysqlserverteam.com/mysql-5-7-12-part-4-a-new-mysql-command-line-shell/), which can use SQL or programming languages (currently limited to Javascript and Python.)

What prevented me from adding mysqlsh straight away is that it can run in three modes (js, py, and SQL), two of which required the X protocol to be active. 
There are several ways of using them automatically, but none is a quick hack. They require some preliminary checks.

* (1) The mysqlsh script should run the initialisation for the protocol.
* (2) We can add a start_x_protocol for sandboxes of MySQL 5.7.12+.
* (3) We add a --enable_x_protocol option to low_level_make_sandbox
* (4) We do nothing, and leave the user to deal with the initialisation.

As for the script name, what should it be?

* (A) pymysqlsh, jsmysqlsh, sqlmysqlsh or mysqlshpy mysqlshjs mysqlshsql
* (B) mysqlsh with a mandatory 1st parameter that must be one of (js py sql)
* (C) mysqlsh with its type defined by start_x_protocol (which would accept a shell_type parameter)

**Comment by yoku0825** [comment]
I'd like (2), similar way of `enable_gtid` and (B).

By the way, can I propose you another way which I'd like to take `mysqlsh` ?

I'd like to use `mysqlsh` via `node/my` script, like other clients.
I think this way is simply and I won't lose how to elect `mysqlsh`, because `node/my` is honestly for given options.

`./master/my sqlsh --sqlc` will connect SQL mode to Master via Classic protocol.
`./node1/my sqlsh --sql` will connect SQL mode to Slave1 via X protocol.

**Comment by datacharmer** [comment]
@yoku0825 , thanks for your comment. 
Currently, connecting with node#/my sqlsh is not feasible because mysqlsh is distributed separately from the server. I hope the MySQL team will add the most updated mysqlsh to the server distribution, so that this method will become possible.

**Comment by morgo** [comment]
Per [this post](http://mysqlserverteam.com/mysql-5-7-12-part-1-more-than-a-maintenance-release/), it's important to point out that there may be other plugins arriving in future.  So it might be worth planning for this at the same time.

Is it possible to move `enable_gtid` and `xprotocol` to a directory called `plugins`?  As part of bootstrap I would like to be able to say:
`make_sandbox mysql*.tar.gz -- --enable-plugins=all`
`make_sandbox mysql*.tar.gz -- --enable-plugins=gtid,xprotocol`

My vote for script name is (b)

**Comment by morgo** [comment]
@datacharmer For mysqlsh to be distributed with the server, it would need to follow the server's release model (no new features after GA, maintain backwards compatible..).  This may happen in future, but I think that it needs a more rapid development cycle for now.

**Comment by datacharmer** [comment]
@morgo It would be enough if the server shipped with the most recent mysqlsh available at release time. It does not need to be tied to the server development timing. This is important to preserve MySQL Sandbox philosophy, where you are guaranteed to run the tool (such as mysqldump, mysqlbinlog) that are adequate for the version you are running. When you use MySQL Sandbox with MySQL 5.7, you get a mysqldump client that understands virtual columns, regardless of what's installed centrally in your host, which could run version 5.1 or 5.5 and would botcher your backups.

Having a centralized mysqlsh client breaks this trust, with two bad consequences:
* you may run a newer mysqlsh with a server version that does not support recent features in the client;
* or you may run an older mysqlsh that's unable to run new protocols supported by a newer server.

For a clean installation of mysqlsh, we need either a copy of the current client to be available in the server tarball, or a sandbox-friendly distribution of the client that can be installed with the same principles.

**Comment by yoku0825** [comment]
@datacharmer 

You're right, I missed that `mysqlsh` isn't include tar-ball package yet.
Over again, I agree your idea (B). (like `node#/mycli` does)
Thanks :)

**Comment by datacharmer** [comment]
This issue is related to [MySQL bug#81187](https://bugs.mysql.com/bug.php?id=81187).

**Comment by simplyianm** [comment]
damn this is cool

cc @albertyw @tejasmanohar

**Comment by datacharmer** [comment]
I have released MySQL Sandbox 3.1.06 with temporary support for mysqlsh. There are at least 3 bugs that prevent a proper installation or decent usability:
* [X-Plugin installed with plugin-load does not accept connections](https://bugs.mysql.com/bug.php?id=81312)
* [Provide a customizable distribution for mysqlsh](https://bugs.mysql.com/bug.php?id=81257)
* [switching session type from classic to JS fails](https://bugs.mysql.com/bug.php?id=81351)

As it is now, there is a mysqlsh script that runs in classic mode. I will rivisit this issue when the above bugs are fixed, or when I find an easy workaround.

**Comment by datacharmer** [comment]
MySQL-Sandbox 3.2.00 adds two changes.

* mysqlsh (with no arguments or with --sql) starts in sql mode
* mysqlsh --js starts in JS mode

This second mode works well when starting the server with the automatic port definition

    make_sandbox 5.7.14 -- --plugin_mysqlx  
(uses port 15714, automatically)
or
    make_sandbox 5.7.14 -- --plugin_mysqlx  --mysqlx_port=24000
(uses a specific port for the X-plugin)

then

    ~/sandboxes/msb_5_7_14/mysqlsh --js [commands]
