### ISSUE TITLE
Add new option `--master_ip` for `make_replication_sandbox`

### ISSUE THREAD

**Issue by renecannao** [datacharmer/mysql-sandbox#21]
`make_replication_sandbox` uses hardcoded `CHANGE MASTER TO master_host='127.0.0.1'`
This isn't a problem itself because the nodes are all local, but there are other factors that can break the setup of replication.
For example:
* using `make_replication_sandbox --remote_access=10.1.2.3` will create a user `rsandbox@10.1.2.3` ;
* using `make_replication_sandbox --node_options="--bind-address=0.0.0.0"` will create all users with `host=0.0.0.0` .
Either way, replication won't setup correctly.

A possible solution is to add a new option `--master_ip` to specify the IP of the master.
Thanks

**Comment by datacharmer** [comment]
Implemented in 3.1.13
