### ISSUE TITLE
Sandbox cannot be started if I overrided pid file in my.sandbox.cnf

### ISSUE THREAD

**Issue by svetasmirnova** [datacharmer/mysql-sandbox#27]
I installed sandbox in local directory, but then needed to move datadir into different disk. I changed my.sandbox.cnf to reflect changes. This works fine. However, if I also move pid file "start" script stops working.

**How to repeat:**

1. `~/build/mysql-sandbox/bin/make_sandbox mysql-5.7.16-linux-glibc2.5-x86_64.tar.gz `
2. Replace 

`pid-file           = /home/sveta/sandboxes/msb_5_7_16/data/mysql_sandbox5716.pid`

with

`pid-file           = /tmp/mysql_sandbox5716.pid`

3. Try to start it:
```

sveta@Thinkie:~/sandboxes/msb_5_7_16$ ./start
................................................................................................................................................................................... sandbox server not started yet
```

**Suggested fix:**

Read pid-file from the configuration file, do not hard code it.

**Comment by datacharmer** [comment]
In the sandbox there is a script to move the sandbox to a different place. 
You are not supposed to do it manually. What looks hardcoded is dynamically generated.

**Comment by svetasmirnova** [comment]
OK, thank you!

This is not as flexible as custom path for each component, but sandbox is not for this flexibility anyway.
