### ISSUE TITLE
Accessing sandbox from linux terminal

### ISSUE THREAD

**Issue by bgth** [datacharmer/mysql-sandbox#28]
Hi,

The sandbox which is created is accessible from the terminal if "--host=127.0.0.1" is added. Without it, it is not working. Is it possible to add that in the ReadMe so that there is no need to look for it anywhere?

mysql -u "username" --host=127.0.0.1 --port=5172 -p

Thanks.

**Comment by datacharmer** [comment]
In the README, there is a section "USING A SANDBOX."
In there it explains that you can just go inside the sandbox and type './use'

Inside the sandbox (for example $HOME/sandboxes/msb_5_1_72) you will also find a file connection.json, containing examples in several languages, including shell.

**Comment by bgth** [comment]
Yeah.. you are right. Thanks. I am closing it now.
