### ISSUE TITLE
Add support for MariaDB 10.2.3

### ISSUE THREAD

**Issue by iangilfillan** [datacharmer/mysql-sandbox#29]
MariaDB 10.2.2 worked fine, but MariaDB 10.2.3 fails with "unsupported version 10.2"

**Comment by datacharmer** [comment]
Thanks for your report.
MySQL Sandbox could not have worked unmodified with 10.2.2, as the 10.2 version is not yet listed among the supported ones.
The next release will include support for 10.2. In the meantime, you can enable support for another version by locating Sandbox.pm and adding the new version:

    $ perldoc -l MySQL::Sandbox
    /usr/local/share/perl/5.22.1/MySQL/Sandbox.pm
    $ sudo vim /usr/local/share/perl/5.22.1/MySQL/Sandbox.pm
    [...]
    my @supported_versions = qw( 3.23 4.0 4.1 5.0 5.1 5.2 5.3 5.4
    5.5 5.6 5.7 5.8 6.0 8.0 10.0 10.1 10.2 );
    [...]

**Comment by iangilfillan** [comment]
Thanks, yes, I do vaguely remember modifying it to work with 10.2.2, and probably overwrote this change when upgrading to the latest release.
