### ISSUE TITLE
make_sandbox_from_installed doesn't support rpm-installation for 64bit environment

### ISSUE THREAD

**Issue by yoku0825** [datacharmer/mysql-sandbox#3]
rpm-installation for 64bit environment is installing libraries into /usr/lib64, but current make_sandbox_from_installed doesn't search $prefix/lib64 .

https://github.com/datacharmer/mysql-sandbox/blob/1650aac5abfe74a1657c1e9e4b64f5cd44ec86e1/bin/make_sandbox_from_installed#L95-L98

**Comment by yoku0825** [comment]
## How to repeat

* On CentOS 6.5 box,

```
$ sudo /usr/local/bin/cpanm MySQL::Sandbox
$ sudo rpm -i http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
$ sudo yum install mysql-community-server-5.6.26
$ make_sandbox_from_installed 5.6.26
```

**Comment by datacharmer** [comment]
Thanks for this report.
Assuming that your patch works for you, and makes the script usable at least in one environment, I am going to accept it. However, this script has more problems than this. 
It fails in many ways on different operating systems. It will need more reengineering to make it right.
