### ISSUE TITLE
cannot start sandboxes

### ISSUE THREAD

**Issue by WilliamAnthony** [datacharmer/mysql-sandbox#32]
I used to start sandboxes successfully at my old linux boxes, ubuntu 14.04 with upstart.
When I try to install it to my new linux box ubuntu 16.04, it failed.

FYI, ubuntu 16.04 comes default with systemd, I thought it would save time, if I just reverted back to upstart. So after I reconfigure it back to upstart, with same configuration with my ubuntu 14.04, I tried to boot the machine and the sandboxes failed to start.

I check at /var/log/upstart, it said:
```
The variable $USER is undefined - aborting
BEGIN failed--compilation aborted at /usr/local/share/perl/5.22.1/MySQL/Sandbox.pm line 74.
Compilation failed in require at /home/edp/sandboxes/sandbox_action line 20.
BEGIN failed--compilation aborted at /home/edp/sandboxes/sandbox_action line 20.
```

I'm using mysql sandbox 3.2.0.5 and mariadb 10.1.22

Please help, what should I do next? Thanks.

**Comment by WilliamAnthony** [comment]
Oh I forgot to mention, I only have problem with automatic start, no problem at all with manual start from console, eg: /home/william/sandboxes/start_all

**Comment by datacharmer** [comment]
The problem that is reported is that the $USER variables is undefined. This variable should be set automatically by the operating system, but for some reason it was not done in your case.
Try setting the $USER variable explicitly before calling make_sandbox:

    export USER=william

**Comment by WilliamAnthony** [comment]
Ok thanks for your response.

I just made an experiment to replace mysql sandbox 3.1.01 at my ubuntu 14.04 box, to the newest one, 3.2.0.5. After that, I rebooted the machine. All sandboxes are not started now. After I reverted back to 3.1.0.1, sandboxes now operated normally.

**Comment by datacharmer** [comment]
Please let me know if the issue you reported was fixed after setting the USER variable.

**Comment by WilliamAnthony** [comment]
after setting USER variable, new error occured

`The variable $HOME is undefined - aborting`

I tried setting HOME variable to /home/william, but the error still exists.

This issue is actually solved on my side, I just simply replace the sandbox with the older version.
Maybe I'll try if the problem still exists at next future version.
Thanks.
