### ISSUE TITLE
Add support for MariaDB 10.3

### ISSUE THREAD

**Issue by iangilfillan** [datacharmer/mysql-sandbox#34]
It's being pushed to the mirrors today

**Comment by pali** [comment]
+1 for MariaDB 10.3 support. Currently I'm getting `unsupported version 10.3`.

**Comment by datacharmer** [comment]
Changes will come over the week-end

**Comment by datacharmer** [comment]
I did not find binaries. If someone has a link, please post it here.
I have nonetheless added 10.3 among the supported versions. I would feel much better if I could test MariaDB 10.3.

**Comment by pali** [comment]
Here are all versions: http://downloads.mariadb.com/MariaDB

**Comment by iangilfillan** [comment]
> I did not find binaries. If someone has a link, please post it here.
> I have nonetheless added 10.3 among the supported versions. I would 
> feel much better if I could test MariaDB 10.3.
>
> —
>
10.3.0 is available from https://downloads.mariadb.org/mariadb/10.3.0/ - 
it wasn't available there until populated on all mirrors, so you 
probably just missed it.

**Comment by datacharmer** [comment]
Thanks for the link. 
MariaDB 10.3 was tested successfully with MySQL-Sandbox 3.2.06.
