### ISSUE TITLE
fail to load grants when .mylogin.cnf has entry against default login path

### ISSUE THREAD

**Issue by Mikiya** [datacharmer/mysql-sandbox#40]
When executing load_grants, it fails with the following error when .mylogin.cnf has entry against default login path:

> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

To repeat the problem, execute mysql_config_editor like below:

```
shell> mysql_config_editor set --user=foo --password
Enter password:

shell> make_sandbox 5.7.18
```

I suggest to add --login-path='' to MYSQL variable within load_grants.

**Comment by Mikiya** [comment]
I was wrong. Adding --login-path='' doesn't solve the problem. Adding --skip-password altogether solved the problem.

**Comment by datacharmer** [comment]
Hi.
This issue has no easy solution. 
mysql_config_editor has unfortunately been designed with total disregard for concurrent instances of MySQL in the same server.
The file created by mysql_config_editor will be used always.
The proposed solution (using --skip-password) is not documented and it defeats the purpose of MySQL-Sandbox, which is to test a fully functional MySQL server.  If --skip-password is documented, please provide a link. It is not good as a global solution, but it could be used for other purposes.

Possible workarounds:
1) Don't use mysql_config_editor
2) Use it and set a default username and password msandbox/msandbox (ugly)
3) Remove the "r" privilege from the file .mylogin.cnf

Possible improvement of MySQL-Sandbox:
* I can only think of a global check for ~/.mylogin.cnf and fail if the file is present (also ugly)

**Comment by Mikiya** [comment]
Hi!

The problem happens only when executing load_grants script, which is executed upon installation. Because --user and --password option overrides credentials specified in --login-path. So, the default login path doesn't a problem when using sandbox via use command etc. On the other hand, load_grants command is executed right after installation when root password has not been set yet. So, it shouldn't set any password when connecting to the server, because the password is blank at this stage. However, when there is a default login path (mysql or client) set by mysql_config_editor, the mysql command, called in load_grants script, will read it. It results in login failure.

Not using mysql_config_editor, the work around 1, can solve the problem. More specifically, not using default login path name (mysql and client) can solve the problem, too.

The work around 2 cannot be applied, because load_grants script doesn't specify any password for root@localhost user.

The work around 3 will completely disable login path functionality. This breaks the documented functionality.

BTW, the effect of --skip prefix is documented here: https://dev.mysql.com/doc/refman/5.7/en/option-modifiers.html

>  The --disable and --skip prefixes and the =0 suffix all have the same effect: They turn the option off. 

The pull requrest I made yesterday will work around this problem. Please review the content of the patch. It check the version of mysql CLI, and if it's 5.6 or above, it adds --skip-password option when  connecting to the server from load_grants script. AFAIK, the mysql client included in 4.0 series accepts --skip-password option. Unfortunately, I don't have older binaries, so cannot see if --skip prefix is accepted by 3.23 series or older.

Kind regards,
Mikiya

**Comment by datacharmer** [comment]
I forgot to mention that I have actually tested your patch, and it doesn't work as expected.
First off, there is a spurious "2" in line 1841 that makes the script fail. That would be an easy fix, but this is not the point.
The point is that after load_grants, the work has just started. All the other scripts generated or used by MySQL-Sandbox will fail because of .mylogin.cnf.
For example:
      `$ make_sandbox 5.7.19 -- --no_show`
      `The MySQL Sandbox,  version 3.2.13`
      `(C) 2006-2017 Giuseppe Maxia`
     ` # Starting server`
      `. sandbox server started`
    ` # Loading grants`
     `mysql: [Warning] Using a password on the command line interface can be insecure. `
     `mysql: [Warning] Using a password on the command line interface can be insecure.`
     `Your sandbox server was installed in $HOME/sandboxes/msb_5_7_19`
    `$ $HOME/sandboxes/msb_5_7_19/use`
     `ERROR 1045 (28000): Access denied for user 'foo'@'localhost' (using password: YES)`
    `$ $HOME/sandboxes/msb_5_7_19/my sqldump --no-data mysql user`
    `mysqldump: Got error: 1045: Access denied for user 'foo'@'localhost' (using password: YES) when trying to connect`

Your patch, even when it works, fixes only one tiny portion of the problem. MySQL-Sandbox needs to work with MySQL from 5.0 to 8.0 (and MariaDB and Percona Server), and it needs to pass [the whole test suite](https://datacharmer.blogspot.com.es/2015/09/how-mysqlsandbox-is-tested-and-tests.html) in at least two operating systems.
I have created my own patch with a global check for .mylogin.cnf, and I will commit it after it passes all the tests.
If I have to choose between breaking MySQL-Sandbox and breaking the half baked product of mysql_config_editor, I choose to break the latter.

**Comment by datacharmer** [comment]
Version 3.2.14 addresses this issue by introducing a global check for ~/.mylogin.cnf
