### ISSUE TITLE
Cant create mysql from already installed MySQL binary

### ISSUE THREAD

**Issue by angelom88** [datacharmer/mysql-sandbox#43]
I am trying to create mysql sandbox from my existing installed mysql in my ubuntu-server vm however I got an error.

`$ make_sandbox_from_installed 5.7.20`
can't find mysql libraries in (/usr /usr/local /usr/local/mysql)

I also tried to execute via sudo command but encountered the same.
`$ sudo make_sandbox_from_installed 5.7.20`
The variable $PWD is undefined - aborting
BEGIN failed--compilation aborted at /usr/local/share/perl/5.22.1/MySQL/Sandbox.pm line 81.
Compilation failed in require at /usr/local/bin/make_sandbox_from_installed line 20.
BEGIN failed--compilation aborted at /usr/local/bin/make_sandbox_from_installed line 20.

I got installed MySQL version 5.7.20 by issuing below command.
`$ mysql --version`
mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper

**Comment by datacharmer** [comment]
Please see Issue#5

**Comment by angelom88** [comment]
Okay got it, Anyway I just used docker for the moment. Thanks!
