### ISSUE TITLE
MariaDB 10.4 cannot be installed

### ISSUE THREAD

**Issue by pali** [datacharmer/mysql-sandbox#46]
make_sandbox for MariaDB 10.4 tarball fails on following error:
```
unpacking mariadb-10.4.0-linux-glibc_214-x86_64.tar.gz
unsupported version 10.4
```

It seems strange that MariaDB 10.4 is unsupported as it is similar/same as MariaDB 10.3. And MariaDB 10.3 is working fine.

**Comment by pali** [comment]
Why it should work? Or rather, why there is whitelist for version prefixes?

Anyway, dbdeployer seems is still not usable as cpan client nor cpanm client is able to install it.

**Comment by pali** [comment]
Patch for MariaDB 10.4 support is there: https://github.com/datacharmer/mysql-sandbox/pull/47

**Comment by datacharmer** [comment]
I have merged the changes. 
Still, this project is not maintained, and I don't want to spend much time running tests for two similar projects. This project is broken for MySQL 8.0.4 and greater.

Could you try installing MariaDB 10.4 with [dbdeployer](https://github.com/datacharmer/dbdeployer) and see if it works for you?

**Comment by pali** [comment]
I'm using MySQL::Sandbox for testing [DBD::MariaDB](http://metacpan.org/pod/DBD::MariaDB) (see https://travis-ci.org/gooddata/DBD-MariaDB) and it is working fine also for MySQL 8.0 (8.4, 8.0.13, ...). Just I needed to repack MySQL .tar.xz package to .tar.gz so MySQL::Sandbox could load it. I think that there is no need to (heavily) test it. Current version works fine and is enough. So "unmaintained status" is not problem. As you can see travis's DBD::MariaDB setup lot of versions of MySQL and MariaDB via MySQL::Sandbox, so think this verify that MySQL::Sandbox is working perfectly.

MariaDB 10.4 needed change from #47 to start working.

Are you going to release current changes in git to cpan?

Ad dbdeployer, I could try to install MariaDB 10.4 with dbdeployer, but just manually (not in fully automated travis setup like it is in DBD::MariaDB).

**Comment by datacharmer** [comment]
Version 3.2.18 [uploaded to CPAN](https://metacpan.org/release/GMAX/MySQL-Sandbox-3.2.18)
I tried MariaDB 10.4 with dbdeployer and the installation is broken, as MariaDB, unlike MySQL 5.7, still creates the empty users and keeps the `password` field. 

One of the internal MySQL-Sandbox tests is broken for the same reason. Anyway, if it works for you, I can upload a new build to CPAN when needed.

FYI [DBD-mysql](https://github.com/dveeden/DBD-mysql/commit/1e5a1bd5e76ed2ec942a0060b879792c3daddf55) has switched from MySQL-Sandbox to dbdeployer.
