### ISSUE TITLE
support for .tar.xz 

### ISSUE THREAD

**Issue by arhi** [datacharmer/mysql-sandbox#48]
some of the distributions are now using .tar.xz instad of .tar.gz e.g. https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.13-linux-glibc2.12-x86_64.tar.xz as it makes archive much smaller. would be useful to support xz just as gz (tar Jxvf insted zxvf for .tar.xz archives) out of the box

**Comment by datacharmer** [comment]
Hi.
This project is unmaintained. 
It has been replaced by [dbdeployer](https://github.com/datacharmer/dbdeployer), which supports `.tar.xz` files.

**Comment by arhi** [comment]
thx giuseppe i totally forgot about dbdeployer :D
