### ISSUE TITLE
replicate sandnox to diffrent host

### ISSUE THREAD

**Issue by Mughees52** [datacharmer/mysql-sandbox#49]
I have two host:
192.168.1.2 and 192.168.1.3 I want 192.168.1.2 to be the master and 192.168.1.3 to be the slave how can i create this kind of replication?

**Comment by datacharmer** [comment]
Notice that the main purpose of MySQL Sandbox is to deploy several nodes in the same host.
Deploying on many hosts is doable, but requires some manual work, and good understanding of how replication works. See [this page](https://metacpan.org/pod/MySQL::Sandbox::Recipes#Remote-Sandboxes) for how to use remote sandboxes.

Finally, be aware that MySQL Sandbox is unmaintained, and you should consider using its replacement, [dbdeployer](https://github.com/datacharmer/dbdeployer).
