### ISSUE TITLE
error while creating grant tables

### ISSUE THREAD

**Issue by Mughees52** [datacharmer/mysql-sandbox#50]
[root@localhost Desktop]# make_replication_sandbox mysql-5.7.11-linux-glibc2.5-i686.tar.gz
installing and starting master
error while creating grant tables

error installing the master

(512 )

**Comment by Mughees52** [comment]
[root@localhost Desktop]# make_sandbox /root/Desktop/mysql-5.7.11-linux-glibc2.5-i686.tar.gz 
unpacking /root/Desktop/mysql-5.7.11-linux-glibc2.5-i686.tar.gz
Executing low_level_make_sandbox --basedir=/root/Desktop/5.7.11 \
	--sandbox_directory=msb_5_7_11 \
	--install_version=5.7 \
	--sandbox_port=5711 \
	--no_ver_after_name \
	--my_clause=log-error=msandbox.err
    The MySQL Sandbox,  version 3.0.66
    (C) 2006-2015 Giuseppe Maxia
Installing with the following parameters:
upper_directory                = /root/sandboxes
sandbox_directory              = msb_5_7_11
sandbox_port                   = 5711
check_port                     = 
no_check_port                  = 
datadir_from                   = script
install_version                = 5.7
basedir                        = /root/Desktop/5.7.11
tmpdir                         = 
my_file                        = 
operating_system_user          = root
db_user                        = msandbox
remote_access                  = 127.%
bind_address                   = 127.0.0.1
ro_user                        = msandbox_ro
rw_user                        = msandbox_rw
repl_user                      = rsandbox
db_password                    = msandbox
repl_password                  = rsandbox
my_clause                      = log-error=msandbox.err
master                         = 
slaveof                        = 
high_performance               = 
prompt_prefix                  = mysql
prompt_body                    =  [\h] {\u} (\d) > 
force                          = 
no_ver_after_name              = 1
verbose                        = 
load_grants                    = 1
no_load_grants                 = 
no_run                         = 
no_show                        = 
do you agree? ([Y],n) 
error while creating grant tables

This is what my error is showing while i tried to create a sandbox just "ERROR: error while creating grant tables"

**Comment by datacharmer** [comment]
One possible explanation is that you are using a 32-bit tarballs on a 64-bits Linux machine

**Comment by Mughees52** [comment]
Thank you for the update, I was using the latest Mysql tar ball (5.7), The problem was solved when I used an older version i.e. mysql-5.6.17-linux-glibc2.5-x86_64.tar.gz
