### ISSUE TITLE
mysql home

### ISSUE THREAD

**Issue by Mughees52** [datacharmer/mysql-sandbox#51]
how do i find mysql home on my rhl6 server  as my sandbox is running fine 

as i don't see it in /usr/bin

**Comment by datacharmer** [comment]
(a) If you installed a single sandbox, it will be in `$HOME/sandboxes/msb_X_X_XX`.
There are several scripts that point to the mysql tools. For example `./use` will allow you to use the `mysql` client.

**NOTICE THAT MySQL-Sandbox IS UNMAINTAINED**
This project is replaced by [dbdeployer](https://github.com/datacharmer/dbdeployer), which is now GA. It can already support almost all MySQL-Sandbox features, plus a few new ones.

(b) if you did not install any sandbox, please use dbdeployer to do it.
