### ISSUE TITLE
perl lib path error

### ISSUE THREAD

**Issue by kevinbin** [datacharmer/mysql-sandbox#7]
➜ ~>msb
Can't locate MySQL/Sandbox.pm in @INC (you may need to install the MySQL::Sandbox module) (@INC contains: /usr/local/Cellar/mysql-sandbox/3.1.00/libexec/lib/perl5 /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/Cellar/mysql-sandbox/3.1.00/libexec/bin/msb line 23.
BEGIN failed--compilation aborted at /usr/local/Cellar/mysql-sandbox/3.1.00/libexec/bin/msb line 23.
➜ ~>less /usr/local/Library/Formula/mysql-sandbox.rb
class MysqlSandbox < Formula
➜ ~>ll /usr/local/Cellar/mysql-sandbox/3.1.00/libexec/lib/perl5/
➜ ~>ll /usr/local/Cellar/mysql-sandbox/3.1.00/lib/perl5/site_perl/
total 0
drwxr-xr-x  3 hongbin  admin   102B 10  3 11:59 5.18.2
drwxr-xr-x  4 hongbin  admin   136B 10 20 09:24 MySQL
➜ ~>ll /usr/local/Cellar/mysql-sandbox/3.1.00/lib/perl5/site_perl/MySQL/
total 104
drwxr-xr-x  4 hongbin  admin   136B 10 20 09:24 Sandbox
-r--r--r--  1 hongbin  admin    50K 10 20 09:24 Sandbox.pm

**Comment by datacharmer** [comment]
This problem occurs when you have more than one Perl installed on your machine, and you have a different PATH as root (where you installed MySQL-Sandbox) and as regular user (where you want to use it.) 
Change your PATH so that the Perl where you have installed MySQL-Sandbox comes first.
For example:

(as root)

    # which perl
    /usr/bin/perl

(As regular user)

    $ which perl
    /opt/local/bin/perl

Make sure that /usr/bin/perl comes before /opt/local/bin/perl in your $PATH

**Comment by kevinbin** [comment]
I used homebrew install mysql-sandbox on mac os 10.11 , only one perl version .

as regular user
```
➜ ~>which perl
/usr/bin/perl
```
```
vi /usr/local/Library/Formula/mysql-sandbox.rb
def install
    # Both variables need to be set. One is compile-time, the other run-time.
    ENV["PERL_LIBDIR"] = libexec/"lib/perl5"
    ENV.prepend_create_path "PERL5LIB", libexec+"lib/perl5"

    system "perl", "Makefile.PL", "PREFIX=#{prefix}"
    system "make", "test", "install"

    bin.install Dir["#{libexec}/bin/*"]
    bin.env_script_all_files(libexec+"bin", :PERL5LIB => ENV["PERL5LIB"])
  end

```


but Sandbox.pm file in /usr/local/Cellar/mysql-sandbox/3.1.00/lib/perl5/site_perl/MySQL

**Comment by datacharmer** [comment]
I don't know who prepared the installation in homebrew, but the outcome does not seem the right one.
The recommended way of installing is this:

    $ sudo su -
    # cpan MySQL::Sandbox

Alternative ways are listed in the [manual](http://search.cpan.org/~gmax/MySQL-Sandbox-3.1.01/lib/MySQL/Sandbox.pm#INSTALLATION) and in the  [cookbook](http://search.cpan.org/~gmax/MySQL-Sandbox-3.1.01/lib/MySQL/Sandbox/Recipes.pm#Installing_MySQL::Sandbox).

**Comment by kevinbin** [comment]
Thank you very much

**Comment by tleish** [comment]
I am running into the same issue.  The above script from homebrew to install this matches the instructions from this repo for installing this.  There's no mention of using cpan to install it.  Which is the "recommended" method of installing?
