### ISSUE TITLE
Doesn't work with paths containing a space

### ISSUE THREAD

**Issue by seanr** [datacharmer/mysql-sandbox#8]
```
Installing with the following parameters:
upper_directory                = /Volumes/Macintosh HD/Users/robertson/sandboxes
sandbox_directory              = msb_5_7_9
sandbox_port                   = 5709
check_port                     = 
no_check_port                  = 
datadir_from                   = script
install_version                = 5.7
basedir                        = /Volumes/Macintosh HD/Users/robertson/Downloads/5.7.9
tmpdir                         = 
my_file                        = 
operating_system_user          = robertson
db_user                        = msandbox
remote_access                  = 127.%
bind_address                   = 127.0.0.1
ro_user                        = msandbox_ro
rw_user                        = msandbox_rw
repl_user                      = rsandbox
db_password                    = msandbox
repl_password                  = rsandbox
my_clause                      = log-error=msandbox.err
master                         = 
slaveof                        = 
high_performance               = 
prompt_prefix                  = mysql
prompt_body                    =  [\h] {\u} (\d) > 
force                          = 
no_ver_after_name              = 1
verbose                        = 
load_grants                    = 1
no_load_grants                 = 
no_run                         = 
no_show                        = 
keep_uuid                      = 
history_dir                    = 
do you agree? ([Y],n) 
Can't exec "/Volumes/Macintosh": No such file or directory at /usr/local/bin/low_level_make_sandbox line 615.
Can't determine MySQL version
```

It actually did create the sandbox folder and there's stuff in it, but I have no idea what it was trying to exec, so I don't know where it actually failed or whether I've got a working sandbox at all.

**Comment by datacharmer** [comment]
Can you show the command you used to run make_sandbox?
Also, please show the result of
echo $HOME

**Comment by datacharmer** [comment]
A quick workaround would be the following:

1. remove everything from the sandbox directory (msb_5_7_9) and the directory itself
2. make sure that the path in $HOME does not have a space (if it is "/Volumes/Macintosh HD/Users/robertson", change it to "/Users/robertson"
3. run make_sandbox ~/Downloads/5.7.9

**Comment by seanr** [comment]
This was my command:

make_sandbox ~/Downloads/mysql-5.7.9-osx10.10-x86_64.tar.gz

I was able to do it by creating a symlink and the temporarily setting $HOME to that (my home directory is on a separate drive as it's too big to fit on my SSD).  Frustrating, though - ideally this would properly respect all possible valid paths.

**Comment by datacharmer** [comment]
In OSX, the $HOME variable should always be /Users/user_name. In this configuration, everything works out of the box (my main test suite is on my mac.)
This is the first time I see the path expanded to include "Volumes/Macintosh HD." Is it OSX 10.11?
For now, apart from the workaround above, I can't offer a better fix.

**Comment by datacharmer** [comment]
An early check was added to MySQL::Sandbox module. If the HOME variable contains spaces, the module load will abort with an appropriate message.
